export const TestFaucetABI = [
  {
    inputs: [
      { name: "_testUsdc", type: "address" },
      { name: "_propertyToken", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "CooldownNotPassed", type: "error" },
  { inputs: [], name: "InsufficientFaucetBalance", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [{ name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [{ name: "propertyId", type: "uint256" }], name: "PropertyNotAvailable", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "usdcAmount", type: "uint256" },
      { indexed: false, name: "propertyAmount", type: "uint256" },
    ],
    name: "ClaimAmountsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "newCooldown", type: "uint256" }],
    name: "CooldownUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "propertyId", type: "uint256" }],
    name: "PropertyAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "propertyId", type: "uint256" }],
    name: "PropertyRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "propertyId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "PropertyTokenClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "UsdcClaimed",
    type: "event",
  },
  {
    inputs: [{ name: "propertyId", type: "uint256" }],
    name: "addProperty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "availablePropertyIds",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "propertyId", type: "uint256" }],
    name: "claimPropertyTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimUsdc",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cooldownPeriod",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAvailableProperties",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "propertyId", type: "uint256" }],
    name: "getFaucetBalances",
    outputs: [
      { name: "usdcBalance", type: "uint256" },
      { name: "propertyBalance", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "user", type: "address" },
      { name: "propertyId", type: "uint256" },
    ],
    name: "getPropertyCooldown",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUsdcCooldown",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "isPropertyAvailable",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    name: "lastPropertyClaim",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "lastUsdcClaim",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "propertyToken",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "propertyTokenClaimAmount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "propertyId", type: "uint256" }],
    name: "removeProperty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_usdcAmount", type: "uint256" },
      { name: "_propertyAmount", type: "uint256" },
    ],
    name: "setClaimAmounts",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_cooldown", type: "uint256" }],
    name: "setCooldownPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "testUsdc",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdcClaimAmount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "propertyId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    name: "withdrawPropertyTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "withdrawUsdc",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
      { name: "", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", type: "bytes4" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
      { name: "", type: "uint256[]" },
      { name: "", type: "uint256[]" },
      { name: "", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", type: "bytes4" }],
    stateMutability: "pure",
    type: "function",
  },
] as const;
